version: '3.2'
services:
  sql-server-db:
    container_name: sql-server-db
    # image: mcr.microsoft.com/mssql/server:2019-latest
    build:
      context: ./database
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'localDev1234!#'
      ACCEPT_EULA: 'Y'
    stdin_open: true
    tty: true
  app:
    depends_on:
      - sql-server-db
    # build: .
    image: docker.io/vgeny/node-web-app
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - TYPEORM_HOST=sql-server-db
    stdin_open: true
    tty: true
